### PR TITLE
Add margaritis to people

### PR DESCRIPTION
**Pull request by margaritis**
Add margaritis to people
Add margaritis image,
Fix the line for the win :stuck_out_tongue:

### CODE REVIEW

**Comment by thanpolas** [comment]
@margaritis sorry conflict

**Comment by margaritis** [comment]
@thanpolas No conflict as of now. I tried to merge locally and it worked flawlessly so most probably it was some delay from Github. I haven't change anything.

**Comment by thanpolas** [comment]
1. There was a PR merged from Adonis which caused the conflict, fetch origin and merge with `origin/master`
1. Reposition your snippet so it's alphabetically ordered (position it after Keloglou

**Comment by margaritis** [comment]
I saw the PR from Adonis. Merging it locally caused no conflict. I will change the order.

**Comment by thanpolas** [comment]
when ready do a new PR

**Pull request closed without merging**
