### PR TITLE
Add Tech Ministry as a community

### PR DESCRIPTION
**Pull request by alexdor**
Include Tech Ministry at communities.yaml

### CODE REVIEW

**Comment by kbariotis** [comment]
We should think of something else to promote Techministry @alexdor . It's different from the other communities. We are open to ideas. :)

**Comment by alexdor** [comment]
Glad to hear that you would like to promote Tech Ministry :smile: .  Off the top of my head, you could promote it with the following ways:
 - by providing exposure (social media shares, blog post, etc.). 
 - by bringing SKGTech and Tech Ministry "closer" (work on common projects, co-host events or something along those lines).

Additionally, you could also help Tech Ministry by providing feedback or by making suggestions. What is your opinion about the aforementioned  proposals? Are there any additional ideas that you would like to propose?

@bacharakis @KostasBlank @AchillesKal  any ideas?

**Comment by kbariotis** [comment]
I was referring to the site @alexdor. Because Tech Ministry is different than the other communities, maybe we could think of something to put it in a different section. Not sure though, just brainstorming here.

Ofc we are already exposing your events and we are willing to work on common projects. :D

**Comment by KostasBlank** [comment]
Another idea would be to create a different section on the skgtech.io website: Spaces.
This section there could have a different layout and include more info about the space

**Comment by alexdor** [comment]
Sorry @kbariotis my bad, I thought it was a general question. Regarding the website, @KostasBlank idea sounds interesting, perhaps there could be a button (or an anchor) "Have you checked our local hackerspace?" that would point to www.techministry.gr. Of course, this is just brainstorming.

**Comment by kbariotis** [comment]
@attheodo is working on a new revision of the site. What do you think?

**Pull request merged**
