### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ntemposd**
delete Open Startup Showcase meetup (it was about time)

### CODE REVIEW

**Comment by thanpolas** [comment]
ABALAEAEAEAEA!

**Comment by ntemposd** [comment]
T egine? Ekana mallon pull request prin kanw commit?

Doylepse? Akoma panw to vlepw

ntemposd.me

**Comment by ntemposd** [comment]
den katalava ti egine.. egw ena commit ekana kai auto to rimadi 7 evgale. Orkizomai oti peiraksa mono to meetups.yaml kai zitaw na min me apolusete :dancer:

**Comment by ntemposd** [comment]
to kleinw twra :dancers:

**Pull request closed without merging**
